apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    pod-identity.alibabacloud.com/injection: 'on'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qytangsa
  namespace: default
  annotations:
    pod-identity.alibabacloud.com/role-name: qytang-ack-role