apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.authService.serviceName }}
  namespace: {{ .Values.deployments.namespace }}
spec:
  selector:
    app: {{ .Values.deployments.authService.app }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.deployments.authService.servicePort }}
      targetPort: {{ .Values.deployments.authService.containerPort }}
      nodePort: {{ .Values.deployments.authService.servicePort }}