apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.cacheService.serviceName }}
  namespace: {{ .Values.deployments.namespace }}
spec:
  selector:
    app: {{ .Values.deployments.cacheService.app }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.deployments.cacheService.servicePort }}
      targetPort: {{ .Values.deployments.cacheService.containerPort }}
      nodePort: {{ .Values.deployments.cacheService.servicePort}}
