{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.secretsDocker.name }}*/}}
{{/*  namespace: {{ .Values.secretsDocker.namespace }}*/}}
{{/*type: kubernetes.io/dockerconfigjson*/}}
{{/*data:*/}}
{{/*  .dockerconfigjson: {{ .Values.secretsDocker.dockerConfigJson }}*/}}