apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.getItemsService.serviceName }}
  namespace: {{ .Values.deployments.namespace }}
spec:
  selector:
    app: {{ .Values.deployments.getItemsService.app }}
{{/*  type: NodePort*/}}
  ports:
    - protocol: TCP
      port: {{ .Values.deployments.getItemsService.servicePort }}
      targetPort: {{ .Values.deployments.getItemsService.containerPort }}
{{/*      nodePort: {{ .Values.deployments.getItemsService.nodePort }}*/}}