apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployments.nginxService.serviceName }}
  namespace: {{ .Values.deployments.namespace }}
spec:
  selector:
    app: {{ .Values.deployments.nginxService.app }}
{{/*  type: NodePort*/}}
  ports:
    - protocol: TCP
      port: {{ .Values.deployments.nginxService.servicePort }}
      targetPort: {{ .Values.deployments.nginxService.containerPort }}
{{/*      nodePort: {{ .Values.deployments.nginxService.nodePort }}*/}}