apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.postItemsService.name }}
  namespace: {{ .Values.deployments.namespace }}
  labels:
    app: {{ .Values.deployments.postItemsService.app }}
spec:
  replicas: {{ .Values.deployments.postItemsService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployments.postItemsService.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.postItemsService.app }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.deployments.postItemsService.image.pullSecret }}
      containers:
      - name: {{ .Values.deployments.postItemsService.name }}
        image: {{ printf "%s/%s:%s" .Values.deployments.imageRepository .Values.deployments.imageName .Values.deployments.postItemsService.image.tag }}
        env:
          - name: DBName
            value: {{ .Values.deployments.dbName }}
          - name: DBHost
            value: {{ .Values.deployments.dbHost }}
          - name: DBUser
            value: {{ .Values.deployments.dbUser }}
          - name: DBPass
            value: {{ .Values.deployments.dbPass }}