{{/*apiVersion: v1*/}}
{{/*kind: Namespace*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.serviceAccount.namespace }}*/}}
{{/*  labels:*/}}
{{/*    pod-identity.alibabacloud.com/injection: 'on'*/}}

{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ServiceAccount*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.serviceAccount.name }}*/}}
{{/*  namespace: {{ .Values.serviceAccount.namespace }}*/}}
{{/*  annotations:*/}}
{{/*    pod-identity.alibabacloud.com/role-name: {{ .Values.serviceAccount.roleName }}*/}}